apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-xehxulub
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-xehxulub:963c198c9e29f170c85fe4e91224b18d069ed347@sha256:8725a7ce7b643431f0d7af6476f09979ad6c95f4b2453905bad10bf7cd846a57
          name: container-image
